import { GearItem, Perk } from './types';

export const PERK_CATALOG: Perk[] = [
  {
    id: 'perk_lifesteal',
    name: 'Vampiric Touch',
    description: 'Restore 18% of damage dealt on critical strikes.',
    icon: 'HeartPulse',
    tier: 3,
    effectType: 'lifesteal',
    magnitude: 0.18,
  },
  {
    id: 'perk_crit_damage',
    name: 'Precision Edge',
    description: 'Increases critical strike damage by +45%.',
    icon: 'Target',
    tier: 2,
    effectType: 'crit_damage',
    magnitude: 0.45,
  },
  {
    id: 'perk_shadow_generation',
    name: 'Shadow Resonance',
    description: 'Generates +35% more Shadow Energy upon landing or taking hits.',
    icon: 'Sparkles',
    tier: 2,
    effectType: 'shadow_generation',
    magnitude: 0.35,
  },
  {
    id: 'perk_damage_reduction',
    name: 'Iron Citadel',
    description: 'Reduces incoming physical damage by 20%.',
    icon: 'Shield',
    tier: 1,
    effectType: 'damage_reduction',
    magnitude: 0.20,
  },
  {
    id: 'perk_unbreakable_poise',
    name: 'Unstoppable Force',
    description: 'Gain unbreakable hyper-armor during the startup of heavy attacks.',
    icon: 'ShieldAlert',
    tier: 3,
    effectType: 'unbreakable_poise',
    magnitude: 1.0,
  },
  {
    id: 'perk_combo_surge',
    name: 'Flowing River',
    description: 'Every hit in a combo increases subsequent damage by +8% (stacks up to 40%).',
    icon: 'Flame',
    tier: 2,
    effectType: 'combo_surge',
    magnitude: 0.08,
  },
];

export const HELMET_CATALOG: GearItem[] = [
  {
    id: 'h_abyssal_crown',
    name: 'Abyssal Overlord Crown',
    slot: 'helm',
    rarity: 'mythic',
    faction: 'heralds',
    level: 7,
    basePower: 390,
    defenseBonus: 110,
    shadowBonus: 140,
    critChance: 0.12,
    description: 'Horned circlet channeling celestial shadow energy directly into the mind.',
    lore: 'Worn by the master of the Shadow Sphere when the rift was torn open.',
    colorScheme: {
      primary: '#0f172a',
      secondary: '#6366f1',
      glow: '#818cf8',
    },
    perks: ['perk_shadow_generation'],
    iconName: 'Crown',
  },
  {
    id: 'h_legion_greathelm',
    name: 'Dread Iron Greathelm',
    slot: 'helm',
    rarity: 'legendary',
    faction: 'legion',
    level: 6,
    basePower: 340,
    defenseBonus: 155,
    shadowBonus: 50,
    description: 'Riveted steel helm with a narrow vision slit that withstands siege weapons.',
    lore: 'Forged in the underground forges of the Bastion Fortress.',
    colorScheme: {
      primary: '#334155',
      secondary: '#94a3b8',
      glow: '#f59e0b',
    },
    perks: ['perk_damage_reduction'],
    iconName: 'Shield',
  },
  {
    id: 'h_dynasty_dragon_mask',
    name: 'Dragon Spirit Mask',
    slot: 'helm',
    rarity: 'epic',
    faction: 'dynasty',
    level: 4,
    basePower: 280,
    defenseBonus: 95,
    shadowBonus: 90,
    critChance: 0.08,
    description: 'Carved lacquered mask depicting the golden celestial serpent.',
    lore: 'Given to imperial tournament champions at the capital court.',
    colorScheme: {
      primary: '#14532d',
      secondary: '#eab308',
      glow: '#4ade80',
    },
    perks: ['perk_combo_surge'],
    iconName: 'Smile',
  },
];

export const ARMOR_CATALOG: GearItem[] = [
  {
    id: 'a_void_shroud',
    name: 'Void Weaver Robes',
    slot: 'armor',
    rarity: 'mythic',
    faction: 'heralds',
    level: 7,
    basePower: 480,
    defenseBonus: 180,
    shadowBonus: 160,
    critChance: 0.10,
    description: 'Silken vestments woven from cosmic shadow filaments and dark matter.',
    lore: 'Allows the wearer to glide between light and darkness without a whisper.',
    colorScheme: {
      primary: '#18181b',
      secondary: '#8b5cf6',
      glow: '#c084fc',
    },
    perks: ['perk_shadow_generation', 'perk_crit_damage'],
    iconName: 'Shirt',
  },
  {
    id: 'a_legion_plate',
    name: 'Juggernaut Bastion Plate',
    slot: 'armor',
    rarity: 'legendary',
    faction: 'legion',
    level: 6,
    basePower: 440,
    defenseBonus: 240,
    shadowBonus: 70,
    description: 'Heavy layered steel cuirass inscribed with anti-sorcery runes.',
    lore: 'Built to survive devastating magical assaults on the frontlines.',
    colorScheme: {
      primary: '#1e293b',
      secondary: '#d97706',
      glow: '#fbbf24',
    },
    perks: ['perk_damage_reduction', 'perk_unbreakable_poise'],
    iconName: 'ShieldAlert',
  },
  {
    id: 'a_dynasty_gi',
    name: 'Windwalker Imperial Gi',
    slot: 'armor',
    rarity: 'epic',
    faction: 'dynasty',
    level: 4,
    basePower: 320,
    defenseBonus: 140,
    shadowBonus: 100,
    critChance: 0.08,
    description: 'Lightweight reinforced silk tailored for supreme aerial agility.',
    lore: 'Preferred by royal assassins and grandmasters of the Crane school.',
    colorScheme: {
      primary: '#042f2e',
      secondary: '#0d9488',
      glow: '#2dd4bf',
    },
    perks: ['perk_combo_surge'],
    iconName: 'Sparkles',
  },
];

export const RANGED_CATALOG: GearItem[] = [
  {
    id: 'r_shadow_kunai',
    name: 'Spectral Shadow Kunai',
    slot: 'ranged',
    rarity: 'legendary',
    faction: 'heralds',
    level: 6,
    basePower: 260,
    attackBonus: 110,
    shadowBonus: 75,
    critChance: 0.20,
    description: 'Phasing throwing blades that pierce physical armor directly into the soul.',
    lore: 'Leaves a trail of ethereal violet smoke before re-materializing in hand.',
    colorScheme: {
      primary: '#2e1065',
      secondary: '#a855f7',
      glow: '#d8b4fe',
    },
    perks: ['perk_crit_damage'],
    iconName: 'Crosshair',
  },
  {
    id: 'r_throwing_axes',
    name: 'Legion War Cleaver Axes',
    slot: 'ranged',
    rarity: 'epic',
    faction: 'legion',
    level: 5,
    basePower: 240,
    attackBonus: 125,
    defenseBonus: 25,
    description: 'Heavy throwing tomahawks that stagger charging beasts and warriors.',
    lore: 'Standard ordinance for frontline shock vanguard units.',
    colorScheme: {
      primary: '#44403c',
      secondary: '#ea580c',
      glow: '#fb923c',
    },
    perks: ['perk_damage_reduction'],
    iconName: 'Axe',
  },
];
