import { StoryStage } from './types';
import { WEAPON_CATALOG } from './weapons';
import { HELMET_CATALOG, ARMOR_CATALOG, RANGED_CATALOG } from './armor';

export const STORY_CAMPAIGN: StoryStage[] = [
  // --- ACT I: BASTION OF THE LEGION ---
  {
    id: 'stage_1_1',
    act: 1,
    chapter: 1,
    title: 'The Outpost Breach',
    subtitle: 'Act I: Bastion of the Legion',
    loreIntro: 'The Iron Legion has sealed the outer borders. A rogue shadow rift has corrupted the frontier vanguard.',
    arenaBackground: 'burning_citadel',
    enemy: {
      name: 'Vanguard Sergeant Marcus',
      title: 'Corrupted Iron Vanguard',
      faction: 'legion',
      stats: {
        health: 5800,
        maxHealth: 5800,
        shadowEnergy: 0,
        maxShadowEnergy: 100,
        attackPower: 82,
        defense: 110,
        shadowPower: 50,
        critChance: 0.14,
        critMultiplier: 1.55,
        poise: 110,
      },
      weapon: WEAPON_CATALOG.find((w) => w.id === 'w_claymore_ironclad') || WEAPON_CATALOG[0],
      armor: ARMOR_CATALOG.find((a) => a.id === 'a_legion_plate') || ARMOR_CATALOG[0],
      helm: HELMET_CATALOG.find((h) => h.id === 'h_legion_greathelm') || HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'aggressive',
    },
    dialogueBefore: [
      {
        speaker: 'Vanguard Marcus',
        avatar: 'ShieldAlert',
        text: 'Halt, wanderer! The Shadow Core is quarantined. None pass through the Iron Bastion alive!',
        side: 'right',
      },
      {
        speaker: 'You (Shadow Initiate)',
        avatar: 'Sword',
        text: 'Your mind has already succumbed to the rift, Marcus. Step aside or be freed by steel.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Vanguard Marcus',
        avatar: 'ShieldAlert',
        text: 'Ugh... the darkness in my veins... you wield the pure shadow... Commander Ironclad awaits you at the Citadel...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 650,
      shadowCores: 50,
      gear: WEAPON_CATALOG[4], // War hammer
    },
  },
  {
    id: 'stage_1_2',
    act: 1,
    chapter: 2,
    title: 'The Molten Foundry',
    subtitle: 'Act I: Bastion of the Legion',
    loreIntro: 'Deep within the subterranean magma crucibles of the Legion, Forge Warden Ignis crafts meteorite plate for the vanguard.',
    arenaBackground: 'volcanic_abyss',
    enemy: {
      name: 'Forge Warden Ignis',
      title: 'Master of the Magma Anvil',
      faction: 'legion',
      stats: {
        health: 7200,
        maxHealth: 7200,
        shadowEnergy: 20,
        maxShadowEnergy: 100,
        attackPower: 96,
        defense: 135,
        shadowPower: 60,
        critChance: 0.16,
        critMultiplier: 1.6,
        poise: 130,
      },
      weapon: WEAPON_CATALOG[4], // Titanbreaker War Hammer
      armor: ARMOR_CATALOG[1],
      helm: HELMET_CATALOG[1],
      ranged: RANGED_CATALOG[1],
      aiPersonality: 'aggressive',
    },
    dialogueBefore: [
      {
        speaker: 'Forge Warden Ignis',
        avatar: 'ShieldAlert',
        text: 'You dare step into the Sacred Magma Crucible? The fires here smelt raw ore and vaporize frail shadow-walkers!',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'The shadows are tempered by heat, blacksmith. Strike if you must.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Forge Warden Ignis',
        avatar: 'ShieldAlert',
        text: 'Unbelievable... your strikes quenched my forge hammer... General Ironclad waits at the High Gates...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 900,
      shadowCores: 80,
      gear: ARMOR_CATALOG[1],
    },
  },
  {
    id: 'stage_1_3',
    act: 1,
    chapter: 3,
    title: 'Trial of the Heavy Gate',
    subtitle: 'Act I: Bastion of the Legion',
    loreIntro: 'At the grand gates of the Citadel, General Ironclad tests whether your blade is worthy of the Legion secrets.',
    arenaBackground: 'burning_citadel',
    enemy: {
      name: 'General Ironclad',
      title: 'The Unbreakable Champion',
      faction: 'legion',
      stats: {
        health: 9400,
        maxHealth: 9400,
        shadowEnergy: 30,
        maxShadowEnergy: 100,
        attackPower: 110,
        defense: 165,
        shadowPower: 75,
        critChance: 0.20,
        critMultiplier: 1.70,
        poise: 160,
      },
      weapon: WEAPON_CATALOG[1], // Bastion Claymore
      armor: ARMOR_CATALOG[1],
      helm: HELMET_CATALOG[1],
      ranged: RANGED_CATALOG[1],
      aiPersonality: 'aggressive',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'General Ironclad',
        avatar: 'ShieldAlert',
        text: 'You fight well for a shadow wielder. But our armor is forged in celestial meteorites. Let us test your resolve!',
        side: 'right',
      },
      {
        speaker: 'You (Shadow Initiate)',
        avatar: 'Sword',
        text: 'Iron bends when faced with the void. Ready your stance, General.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'General Ironclad',
        avatar: 'ShieldAlert',
        text: 'Magnificent... your strikes shattered my poise. Vanguard Marcus will join your ranks. Seek the Dynasty Pagoda in the eastern lands.',
        side: 'right',
      },
    ],
    rewards: {
      gold: 1300,
      shadowCores: 130,
      gear: ARMOR_CATALOG[1],
      unlocksCharacterId: 'char_marcus',
    },
  },

  // --- ACT II: JADE PAVILIONS & MISTY SHRINES ---
  {
    id: 'stage_2_1',
    act: 2,
    chapter: 1,
    title: 'The Bamboo Mist',
    subtitle: 'Act II: Jade Pavilions',
    loreIntro: 'The air smells of burning incense and damp bamboo. The Dynasty Shadow Monks guard the sacred pagoda.',
    arenaBackground: 'dynasty_palace',
    enemy: {
      name: 'Monk Ling',
      title: 'Grandmaster of the Gale',
      faction: 'dynasty',
      stats: {
        health: 10500,
        maxHealth: 10500,
        shadowEnergy: 30,
        maxShadowEnergy: 100,
        attackPower: 122,
        defense: 140,
        shadowPower: 120,
        critChance: 0.28,
        critMultiplier: 1.85,
        poise: 110,
      },
      weapon: WEAPON_CATALOG[2], // Nunchaku
      armor: ARMOR_CATALOG[2],
      helm: HELMET_CATALOG[2],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'counter_master',
    },
    dialogueBefore: [
      {
        speaker: 'Monk Ling',
        avatar: 'Flame',
        text: 'Shadow is like water, traveler. It flows around brute strength. Can your blade cut the wind?',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'Water cuts mountains given time. Show me your form, monk.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Monk Ling',
        avatar: 'Flame',
        text: 'Harmonious and deadly. You have mastered the gale. Proceed into the blood grove beyond!',
        side: 'right',
      },
    ],
    rewards: {
      gold: 1600,
      shadowCores: 160,
      gear: WEAPON_CATALOG[2],
      unlocksCharacterId: 'char_ling',
    },
  },
  {
    id: 'stage_2_2',
    act: 2,
    chapter: 2,
    title: 'Autumn Blood Grove',
    subtitle: 'Act II: Jade Pavilions',
    loreIntro: 'Beneath the great Blood Lantern Moon, silent shadows flit through the crimson bamboo groves.',
    arenaBackground: 'crimson_bamboo',
    enemy: {
      name: 'Shadow Assassin Kitsune',
      title: 'Phantom of the Red Mist',
      faction: 'dynasty',
      stats: {
        health: 11800,
        maxHealth: 11800,
        shadowEnergy: 35,
        maxShadowEnergy: 100,
        attackPower: 135,
        defense: 145,
        shadowPower: 135,
        critChance: 0.32,
        critMultiplier: 1.95,
        poise: 105,
      },
      weapon: WEAPON_CATALOG[5], // Dual Daggers
      armor: ARMOR_CATALOG[2],
      helm: HELMET_CATALOG[2],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'counter_master',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Kitsune',
        avatar: 'Flame',
        text: 'The fallen crimson leaves hide the scent of blood. You will never hear the twin blades that end your voyage.',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'Speed is futile if your target has already foreseen your shadow.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Kitsune',
        avatar: 'Flame',
        text: 'Incredible... you parried the phantom thrusts. Seek the ancient Dragon Pagoda at the summit!',
        side: 'right',
      },
    ],
    rewards: {
      gold: 2000,
      shadowCores: 200,
      gear: WEAPON_CATALOG[5],
    },
  },
  {
    id: 'stage_2_3',
    act: 2,
    chapter: 3,
    title: 'The Jade Pagoda Summit',
    subtitle: 'Act II: Jade Pavilions',
    loreIntro: 'At the uppermost pagoda terrace surrounded by floating lanterns and jade dragon statues, Grandmaster Chen defends the Dynasty Heart.',
    arenaBackground: 'emerald_bamboo_temple',
    enemy: {
      name: 'Grandmaster Chen The Jade Dragon',
      title: 'Warden of the Dragon Pearl',
      faction: 'dynasty',
      stats: {
        health: 13200,
        maxHealth: 13200,
        shadowEnergy: 40,
        maxShadowEnergy: 100,
        attackPower: 142,
        defense: 160,
        shadowPower: 145,
        critChance: 0.30,
        critMultiplier: 2.05,
        poise: 125,
      },
      weapon: WEAPON_CATALOG[2], // Nunchaku
      armor: ARMOR_CATALOG[2],
      helm: HELMET_CATALOG[2],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'counter_master',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Grandmaster Chen',
        avatar: 'Flame',
        text: 'The Jade Dragon pearl channels ten thousand years of Dynasty chi. You must strike like lightning and remain still like jade.',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'My blade is honed by the shadow itself. Let us exchange techniques!',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Grandmaster Chen',
        avatar: 'Flame',
        text: 'Truly transcendent. The dragon yields to your supreme mastery. Climb the Northern Glacial Peaks... the Frost Sanctuary opens to you.',
        side: 'right',
      },
    ],
    rewards: {
      gold: 2400,
      shadowCores: 250,
      gear: WEAPON_CATALOG[2],
    },
  },

  // --- ACT III: THE FROZEN MONASTERY & SUNKEN DEPTHS ---
  {
    id: 'stage_3_1',
    act: 3,
    chapter: 1,
    title: 'The Glacial Ascent',
    subtitle: 'Act III: Frostpeak Sanctuary',
    loreIntro: 'Howling blizzards and shimmering auroras cloak the ancient altar where northern hermits harness cryo-shadow energy.',
    arenaBackground: 'frostpeak_sanctuary',
    enemy: {
      name: 'Grandmaster Boreas',
      title: 'Warden of the Arctic Shroud',
      faction: 'dynasty',
      stats: {
        health: 14500,
        maxHealth: 14500,
        shadowEnergy: 40,
        maxShadowEnergy: 100,
        attackPower: 148,
        defense: 165,
        shadowPower: 155,
        critChance: 0.32,
        critMultiplier: 2.1,
        poise: 130,
      },
      weapon: WEAPON_CATALOG[0], // Void Katana (Frost infused)
      armor: ARMOR_CATALOG[2],
      helm: HELMET_CATALOG[2],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'tactical',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Grandmaster Boreas',
        avatar: 'Zap',
        text: 'The frost freezes all mortal hesitation. Few survive the biting blizzard of Frostpeak.',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'My shadow fire will melt your ice. Stand ready!',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Grandmaster Boreas',
        avatar: 'Zap',
        text: 'The ice thaws before your resolve... Deep beneath the glaciers lie the Sunken Abyss Spires. Beware Nerida...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 2800,
      shadowCores: 280,
      gear: HELMET_CATALOG[2],
    },
  },
  {
    id: 'stage_3_2',
    act: 3,
    chapter: 2,
    title: 'The Abyssal Rift Spires',
    subtitle: 'Act III: The Sunken Shrines',
    loreIntro: 'Deep in subterranean oceanic caverns, bioluminescent cyan crystals illuminate the forgotten sunken altars of the Void Sirens.',
    arenaBackground: 'sunken_shadow_abyss',
    enemy: {
      name: 'High Priestess Nerida',
      title: 'Voice of the Sunken Rift',
      faction: 'heralds',
      stats: {
        health: 15800,
        maxHealth: 15800,
        shadowEnergy: 45,
        maxShadowEnergy: 100,
        attackPower: 154,
        defense: 175,
        shadowPower: 168,
        critChance: 0.34,
        critMultiplier: 2.15,
        poise: 135,
      },
      weapon: WEAPON_CATALOG[3], // Bloodweaver Kusarigama
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'tactical',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Priestess Nerida',
        avatar: 'Zap',
        text: 'The sunken depths echo with the heartbeat of forgotten gods. Your blade will rust in these dark waters!',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'Darkness is my ally. Your tides cannot drown the shadow.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Priestess Nerida',
        avatar: 'Zap',
        text: 'Such unyielding power... The subterranean currents yield. The Celestial Stargate is aligning in the heavens above. Ascend!',
        side: 'right',
      },
    ],
    rewards: {
      gold: 3200,
      shadowCores: 320,
      gear: WEAPON_CATALOG[3],
    },
  },

  // --- ACT IV: HERALD VOID CORE & THUNDER OBSERVATORY ---
  {
    id: 'stage_4_1',
    act: 4,
    chapter: 1,
    title: 'The Astral Stargate',
    subtitle: 'Act IV: Celestial Observatory',
    loreIntro: 'Floating among infinite constellations, the Heralds have engineered orbital gates that harvest raw stellar void energy.',
    arenaBackground: 'astral_observatory',
    enemy: {
      name: 'Cyber Centurion Nexus',
      title: 'Guardian of the Astrolabe',
      faction: 'heralds',
      stats: {
        health: 17200,
        maxHealth: 17200,
        shadowEnergy: 45,
        maxShadowEnergy: 100,
        attackPower: 162,
        defense: 180,
        shadowPower: 175,
        critChance: 0.34,
        critMultiplier: 2.1,
        poise: 140,
      },
      weapon: WEAPON_CATALOG[0], // Void Katana
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'tactical',
    },
    dialogueBefore: [
      {
        speaker: 'Centurion Nexus',
        avatar: 'Zap',
        text: 'Mortal organic wielder detected. Calibrating singularity cannons for immediate annihilation.',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'Your algorithms cannot calculate the depth of human willpower.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Centurion Nexus',
        avatar: 'Zap',
        text: 'Calculation error... power grid collapsing... High Arbiter Kibo awaits inside the Prime Singularity...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 3600,
      shadowCores: 380,
      gear: ARMOR_CATALOG[0],
    },
  },
  {
    id: 'stage_4_2',
    act: 4,
    chapter: 2,
    title: 'The Herald Singularity',
    subtitle: 'Act IV: Herald Void Core',
    loreIntro: 'Inside the floating cyber-citadel of the Heralds, shadow energy is distilled into concentrated dimensional lasers.',
    arenaBackground: 'herald_nexus',
    enemy: {
      name: 'High Arbiter Kibo',
      title: 'Shadow Weaver Prime',
      faction: 'heralds',
      stats: {
        health: 19500,
        maxHealth: 19500,
        shadowEnergy: 50,
        maxShadowEnergy: 100,
        attackPower: 174,
        defense: 195,
        shadowPower: 190,
        critChance: 0.38,
        critMultiplier: 2.2,
        poise: 145,
      },
      weapon: WEAPON_CATALOG[0], // Void Katana
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'tactical',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'High Arbiter Kibo',
        avatar: 'Zap',
        text: 'You have pierced our firewalls and wards. But in the Void Core, spacetime answers only to the Heralds.',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'The shadow belongs to no mortal faction. I will restore balance to the realm.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'High Arbiter Kibo',
        avatar: 'Zap',
        text: 'Unbelievable... the dimensional calculations were flawless... yet your blade struck true. Ascend to the Thunder Altar where Volt Sovereign Raiden tests true deities!',
        side: 'right',
      },
    ],
    rewards: {
      gold: 4200,
      shadowCores: 450,
      gear: HELMET_CATALOG[0],
      unlocksCharacterId: 'char_kibo',
    },
  },
  {
    id: 'stage_4_3',
    act: 4,
    chapter: 3,
    title: 'The Thunder Spire Altar',
    subtitle: 'Act IV: Herald Void Core',
    loreIntro: 'At the apex of the orbital spire where purple lightning storms rip the sky, Volt Sovereign Raiden controls the cosmic electro-grid.',
    arenaBackground: 'celestial_thunder_plateau',
    enemy: {
      name: 'Volt Sovereign Raiden',
      title: 'Overlord of the Storm Nexus',
      faction: 'heralds',
      stats: {
        health: 21500,
        maxHealth: 21500,
        shadowEnergy: 55,
        maxShadowEnergy: 100,
        attackPower: 182,
        defense: 210,
        shadowPower: 200,
        critChance: 0.36,
        critMultiplier: 2.25,
        poise: 155,
      },
      weapon: WEAPON_CATALOG[0], // Void Katana
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'tactical',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Volt Sovereign Raiden',
        avatar: 'Zap',
        text: 'Ten million volts of celestial lightning surge through my veins! Can your sword deflect thunder itself?',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'Thunder is merely sound and light. The shadow swallows all energy whole.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Volt Sovereign Raiden',
        avatar: 'Zap',
        text: 'The thunder calms... you are a true demigod of combat. The Cosmic Eclipse looms ahead... Malakor and Valerius guard the Abyss.',
        side: 'right',
      },
    ],
    rewards: {
      gold: 4800,
      shadowCores: 520,
      gear: WEAPON_CATALOG[0],
    },
  },

  // --- ACT V: THE COSMIC ECLIPSE & THE ABYSS ---
  {
    id: 'stage_5_1',
    act: 5,
    chapter: 1,
    title: 'The Void Maw',
    subtitle: 'Act V: Edge of Oblivion',
    loreIntro: 'At the outer rim of the obsidian event horizon, ancient corrupted behemoths guard the path to the Void Titan.',
    arenaBackground: 'void_colosseum',
    enemy: {
      name: 'Eclipse Dreadnought Malakor',
      title: 'Iron Husk of the Void',
      faction: 'legion',
      stats: {
        health: 24000,
        maxHealth: 24000,
        shadowEnergy: 40,
        maxShadowEnergy: 100,
        attackPower: 190,
        defense: 230,
        shadowPower: 195,
        critChance: 0.28,
        critMultiplier: 2.0,
        poise: 175,
      },
      weapon: WEAPON_CATALOG[3], // Bloodweaver Kusarigama
      armor: ARMOR_CATALOG[1],
      helm: HELMET_CATALOG[1],
      ranged: RANGED_CATALOG[1],
      aiPersonality: 'aggressive',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Malakor',
        avatar: 'Crown',
        text: 'I was once the supreme grand marshal of the Iron Bastion. Now, I am forged in eternal eclipse!',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'I will put your tormented soul to rest, Marshal.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Malakor',
        avatar: 'Crown',
        text: 'Finally... released from the chains of the abyss... Lord Valerius bars the Crimson Eclipse Citadel... proceed with courage...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 5500,
      shadowCores: 650,
      gear: WEAPON_CATALOG[3],
    },
  },
  {
    id: 'stage_5_2',
    act: 5,
    chapter: 2,
    title: 'The Blood Eclipse Gate',
    subtitle: 'Act V: Edge of Oblivion',
    loreIntro: 'Surrounded by gargoyles and bloodstone spires under a pitch black eclipse disc, Crimson Lord Valerius draws strength from the fallen stars.',
    arenaBackground: 'crimson_eclipse_citadel',
    enemy: {
      name: 'Crimson Lord Valerius',
      title: 'Sovereign of the Blood Eclipse',
      faction: 'legion',
      stats: {
        health: 27500,
        maxHealth: 27500,
        shadowEnergy: 55,
        maxShadowEnergy: 100,
        attackPower: 202,
        defense: 245,
        shadowPower: 215,
        critChance: 0.32,
        critMultiplier: 2.2,
        poise: 185,
      },
      weapon: WEAPON_CATALOG[1], // Bastion Claymore
      armor: ARMOR_CATALOG[1],
      helm: HELMET_CATALOG[1],
      ranged: RANGED_CATALOG[1],
      aiPersonality: 'aggressive',
      bossPhases: 2,
    },
    dialogueBefore: [
      {
        speaker: 'Lord Valerius',
        avatar: 'Crown',
        text: 'The Blood Eclipse bathes the heavens in scarlet light. Here, no mortal strike can penetrate my immortal aegis!',
        side: 'right',
      },
      {
        speaker: 'You',
        avatar: 'Sword',
        text: 'Every eclipse must pass. Your reign ends now.',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Lord Valerius',
        avatar: 'Crown',
        text: 'How... can human strength surpass the celestial eclipse?! The Void Titan awakens in the central vortex... Chronos is upon us!',
        side: 'right',
      },
    ],
    rewards: {
      gold: 6500,
      shadowCores: 800,
      gear: ARMOR_CATALOG[1],
    },
  },
  {
    id: 'stage_5_3',
    act: 5,
    chapter: 3,
    title: 'The Void Titan',
    subtitle: 'Act V: The Cosmic Eclipse (Epic Climax)',
    loreIntro: 'Standing on the brink of reality inside the shattered obsidian vortex, the ancient Titan of Shadows emerges to consume the three realms.',
    arenaBackground: 'void_colosseum',
    enemy: {
      name: 'Void Titan Chronos',
      title: 'Harbinger of the Endless Night',
      faction: 'heralds',
      stats: {
        health: 34000,
        maxHealth: 34000,
        shadowEnergy: 65,
        maxShadowEnergy: 100,
        attackPower: 215,
        defense: 270,
        shadowPower: 245,
        critChance: 0.35,
        critMultiplier: 2.35,
        poise: 210,
      },
      weapon: WEAPON_CATALOG[3], // Bloodweaver Kusarigama
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'boss_titans',
      bossPhases: 3,
    },
    dialogueBefore: [
      {
        speaker: 'Void Titan Chronos',
        avatar: 'Crown',
        text: 'INSECT OF DUST. COUNTLESS CHAMPIONS HAVE COME BEFORE YOU. ALL PERISHED BENEATH MY SHADOW ECLIPSE.',
        side: 'right',
      },
      {
        speaker: 'You (Shadow Champion)',
        avatar: 'Sword',
        text: 'I am not just another warrior. I am the convergence of Legion iron, Dynasty wind, and Herald void. Today, your eclipse ends!',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Void Titan Chronos',
        avatar: 'Crown',
        text: 'IMPOSSIBLE... THE SHADOW SPHERE... HAS CHOSEN ITS NEW TRUE MASTER... YET BEYOND THIS REALM, THE PRIMORDIAL STARFORGE CALLS...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 8000,
      shadowCores: 1500,
      gear: WEAPON_CATALOG[1],
      unlocksCharacterId: 'char_chronos',
    },
  },

  // --- ACT VI: PRIMORDIAL GENESIS (ULTIMATE ENDGAME) ---
  {
    id: 'stage_6_1',
    act: 6,
    chapter: 1,
    title: 'The Starforge Singularity',
    subtitle: 'Act VI: Primordial Genesis',
    loreIntro: 'Beyond the mortal spacetime continuum lies the Starforge, where cosmic entities forged the very fabric of shadows and starlight.',
    arenaBackground: 'astral_observatory',
    enemy: {
      name: 'Architect Ouros',
      title: 'Cosmic Smith of Realities',
      faction: 'heralds',
      stats: {
        health: 38000,
        maxHealth: 38000,
        shadowEnergy: 70,
        maxShadowEnergy: 100,
        attackPower: 230,
        defense: 290,
        shadowPower: 260,
        critChance: 0.38,
        critMultiplier: 2.45,
        poise: 220,
      },
      weapon: WEAPON_CATALOG[0], // Void Katana
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'tactical',
      bossPhases: 3,
    },
    dialogueBefore: [
      {
        speaker: 'Architect Ouros',
        avatar: 'Zap',
        text: 'You defeated Chronos, but I am the one who designed the stars and void himself. Prepare to be dismantled into atomic dust.',
        side: 'right',
      },
      {
        speaker: 'You (God of Shadows)',
        avatar: 'Sword',
        text: 'An architect plans, but a warrior lives through battle. Test your creation against my blade!',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Architect Ouros',
        avatar: 'Zap',
        text: 'Splendid... a mortal transcending the blueprints of creation... Sovereign Zero awaits at the primordial origin...',
        side: 'right',
      },
    ],
    rewards: {
      gold: 10000,
      shadowCores: 2000,
      gear: WEAPON_CATALOG[0],
    },
  },
  {
    id: 'stage_6_2',
    act: 6,
    chapter: 2,
    title: 'The Primordial Sovereign',
    subtitle: 'Act VI: Primordial Genesis (Final God Battle)',
    loreIntro: 'At the origin of all existence, Primordial Sovereign Zero commands pure unformed shadows capable of shattering dimensions.',
    arenaBackground: 'crimson_eclipse_citadel',
    enemy: {
      name: 'Primordial Sovereign Zero',
      title: 'God of the Endless Void',
      faction: 'heralds',
      stats: {
        health: 48000,
        maxHealth: 48000,
        shadowEnergy: 85,
        maxShadowEnergy: 100,
        attackPower: 250,
        defense: 320,
        shadowPower: 300,
        critChance: 0.40,
        critMultiplier: 2.6,
        poise: 250,
      },
      weapon: WEAPON_CATALOG[3], // Bloodweaver Kusarigama
      armor: ARMOR_CATALOG[0],
      helm: HELMET_CATALOG[0],
      ranged: RANGED_CATALOG[0],
      aiPersonality: 'boss_titans',
      bossPhases: 3,
    },
    dialogueBefore: [
      {
        speaker: 'Sovereign Zero',
        avatar: 'Crown',
        text: 'BEFORE LIGHT, BEFORE THE NATIONS, I WAS. YOUR BLADE CARRIES THE SUM OF ALL HUMAN VALOR. SHOW ME THE ABSOLUTE PINNACLE OF SHADOW COMBAT!',
        side: 'right',
      },
      {
        speaker: 'You (Shadow Sovereign)',
        avatar: 'Sword',
        text: 'For every warrior that ever fell in the dark... for the future of all three realms... THIS IS MY ULTIMATE STRIKE!',
        side: 'left',
      },
    ],
    dialogueAfter: [
      {
        speaker: 'Sovereign Zero',
        avatar: 'Crown',
        text: 'MAGNIFICENT... THE CYCLE IS COMPLETE. YOU ARE THE TRUE ETERNAL SHADOW SOVEREIGN. THE REALMS ARE FOREVER SAFE IN YOUR HANDS.',
        side: 'right',
      },
    ],
    rewards: {
      gold: 20000,
      shadowCores: 5000,
      gear: WEAPON_CATALOG[0],
      unlocksCharacterId: 'char_chronos',
    },
  },
];
