import { GearItem, WeaponType, GearRarity, Faction } from './types';

export interface MarketplaceSword extends GearItem {
  swordIndex: number;
  hiltOffset: [number, number];
  tipOffset: [number, number];
  spriteUrl: string;
  sprite32Url: string;
  priceGold: number;
  priceGems: number;
  shadowAffinityName: string;
}

export const SWORD_MARKETPLACE_CATALOG: MarketplaceSword[] = [
  {
    id: 'sword_market_0',
    name: 'Legion Apprentice Claymore',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 70,
    attackBonus: 25,
    shadowBonus: 18,
    critChance: 0.16,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 0,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_0.png',
    sprite32Url: '/assets/weapons/items/sword_0_32.png',
    priceGold: 250,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_1',
    name: 'Vanguard Broadsword',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 74,
    attackBonus: 28,
    shadowBonus: 20,
    critChance: 0.18,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 1,
    hiltOffset: [4.3, 90.7],
    tipOffset: [85.7, 9.3],
    spriteUrl: '/assets/weapons/items/sword_1.png',
    sprite32Url: '/assets/weapons/items/sword_1_32.png',
    priceGold: 300,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_2',
    name: 'Silver Needle Rapier',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 1,
    basePower: 78,
    attackBonus: 31,
    shadowBonus: 22,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 2,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_2.png',
    sprite32Url: '/assets/weapons/items/sword_2_32.png',
    priceGold: 350,
    priceGems: 0,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_3',
    name: 'Serpent Dune Scimitar',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 120,
    attackBonus: 60,
    shadowBonus: 54,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 3,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_3.png',
    sprite32Url: '/assets/weapons/items/sword_3_32.png',
    priceGold: 1010,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_4',
    name: 'Hooked Shadow Cleaver',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 4,
    hiltOffset: [7.9, 89.3],
    tipOffset: [87.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_4.png',
    sprite32Url: '/assets/weapons/items/sword_4_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_5',
    name: 'Solar Disk Sabre',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 130,
    attackBonus: 68,
    shadowBonus: 62,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 5,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_5.png',
    sprite32Url: '/assets/weapons/items/sword_5_32.png',
    priceGold: 1250,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_6',
    name: 'Colossus Iron Cleaver',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 5,
    basePower: 187,
    attackBonus: 116,
    shadowBonus: 114,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 6,
    hiltOffset: [4.9, 89.3],
    tipOffset: [85.7, 9.3],
    spriteUrl: '/assets/weapons/items/sword_6.png',
    sprite32Url: '/assets/weapons/items/sword_6_32.png',
    priceGold: 3100,
    priceGems: 15,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_7',
    name: 'Sunfire Scepter Blade',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 194,
    attackBonus: 122,
    shadowBonus: 120,
    critChance: 0.34,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 7,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_7.png',
    sprite32Url: '/assets/weapons/items/sword_7_32.png',
    priceGold: 3350,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_8',
    name: 'Cyan Rune Edge',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 145,
    attackBonus: 80,
    shadowBonus: 78,
    critChance: 0.37,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 8,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_8.png',
    sprite32Url: '/assets/weapons/items/sword_8_32.png',
    priceGold: 1600,
    priceGems: 15,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_9',
    name: 'Flaming Dragon Sabre',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 225,
    attackBonus: 149,
    shadowBonus: 152,
    critChance: 0.38,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ef692f',
      glow: '#ef692f',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 9,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_9.png',
    sprite32Url: '/assets/weapons/items/sword_9_32.png',
    priceGold: 5150,
    priceGems: 45,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_10',
    name: 'Crimson Phoenix Feather',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 159,
    attackBonus: 92,
    shadowBonus: 90,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ef3a0c',
      glow: '#ef3a0c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 10,
    hiltOffset: [4.3, 87.7],
    tipOffset: [90.7, 7.3],
    spriteUrl: '/assets/weapons/items/sword_10.png',
    sprite32Url: '/assets/weapons/items/sword_10_32.png',
    priceGold: 2100,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_11',
    name: 'Abyssal Cobalt Needle',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 166,
    attackBonus: 98,
    shadowBonus: 96,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#3c9f9c',
      glow: '#3c9f9c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 11,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_11.png',
    sprite32Url: '/assets/weapons/items/sword_11_32.png',
    priceGold: 2350,
    priceGems: 15,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_12',
    name: 'Amethyst Void Cleaver',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 195,
    attackBonus: 125,
    shadowBonus: 125,
    critChance: 0.35,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#c084e2',
      secondary: '#2a1d0d',
      glow: '#c084e2',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 12,
    hiltOffset: [4.9, 89.3],
    tipOffset: [79.3, 11.9],
    spriteUrl: '/assets/weapons/items/sword_12.png',
    sprite32Url: '/assets/weapons/items/sword_12_32.png',
    priceGold: 3800,
    priceGems: 45,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_13',
    name: 'Golden Temple Glaive-Sword',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 180,
    attackBonus: 110,
    shadowBonus: 108,
    critChance: 0.37,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efac28',
      glow: '#efac28',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 13,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_13.png',
    sprite32Url: '/assets/weapons/items/sword_13_32.png',
    priceGold: 2850,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_14',
    name: 'Ossuary Bone Cleaver',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 105,
    attackBonus: 48,
    shadowBonus: 42,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 14,
    hiltOffset: [4.3, 90.7],
    tipOffset: [83.1, 10.1],
    spriteUrl: '/assets/weapons/items/sword_14.png',
    sprite32Url: '/assets/weapons/items/sword_14_32.png',
    priceGold: 650,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_15',
    name: 'Dawnbreaker Greatsword',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 8,
    basePower: 225,
    attackBonus: 149,
    shadowBonus: 152,
    critChance: 0.44,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 15,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_15.png',
    sprite32Url: '/assets/weapons/items/sword_15_32.png',
    priceGold: 5150,
    priceGems: 45,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_16',
    name: 'Bloodforged Executioner',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 5,
    basePower: 145,
    attackBonus: 80,
    shadowBonus: 78,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#392a1c',
      glow: '#392a1c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 16,
    hiltOffset: [4.3, 90.7],
    tipOffset: [83.1, 10.1],
    spriteUrl: '/assets/weapons/items/sword_16.png',
    sprite32Url: '/assets/weapons/items/sword_16_32.png',
    priceGold: 1600,
    priceGems: 15,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_17',
    name: 'Jade Wind Katana',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 120,
    attackBonus: 60,
    shadowBonus: 54,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 17,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_17.png',
    sprite32Url: '/assets/weapons/items/sword_17_32.png',
    priceGold: 1010,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_18',
    name: 'Red Lacquer Shinai',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 1,
    basePower: 82,
    attackBonus: 34,
    shadowBonus: 24,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 18,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_18.png',
    sprite32Url: '/assets/weapons/items/sword_18_32.png',
    priceGold: 400,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_19',
    name: 'Emperor Golden Jian',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 205,
    attackBonus: 133,
    shadowBonus: 134,
    critChance: 0.44,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 19,
    hiltOffset: [6.0, 87.8],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_19.png',
    sprite32Url: '/assets/weapons/items/sword_19_32.png',
    priceGold: 4250,
    priceGems: 45,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_20',
    name: 'Vermilion Crossguard',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 135,
    attackBonus: 72,
    shadowBonus: 66,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ef3a0c',
      glow: '#ef3a0c',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 20,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_20.png',
    sprite32Url: '/assets/weapons/items/sword_20_32.png',
    priceGold: 1370,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_21',
    name: 'Jeweled Noble Dao',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 105,
    attackBonus: 48,
    shadowBonus: 42,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 21,
    hiltOffset: [7.9, 89.3],
    tipOffset: [87.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_21.png',
    sprite32Url: '/assets/weapons/items/sword_21_32.png',
    priceGold: 650,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_22',
    name: 'Obsidian Shadow Cleaver',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 187,
    attackBonus: 116,
    shadowBonus: 114,
    critChance: 0.34,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#684c3c',
      glow: '#684c3c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 22,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_22.png',
    sprite32Url: '/assets/weapons/items/sword_22_32.png',
    priceGold: 3100,
    priceGems: 15,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_23',
    name: 'Ruby Heart Dagger',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 115,
    attackBonus: 56,
    shadowBonus: 50,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ef3a0c',
      glow: '#ef3a0c',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 23,
    hiltOffset: [6.0, 87.8],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_23.png',
    sprite32Url: '/assets/weapons/items/sword_23_32.png',
    priceGold: 890,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_24',
    name: 'Silver Willow Estoc',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 1,
    basePower: 86,
    attackBonus: 37,
    shadowBonus: 26,
    critChance: 0.16,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 24,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_24.png',
    sprite32Url: '/assets/weapons/items/sword_24_32.png',
    priceGold: 450,
    priceGems: 0,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_25',
    name: 'Curved Bandit Scimitar',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 25,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_25.png',
    sprite32Url: '/assets/weapons/items/sword_25_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_26',
    name: 'Hextech Crystal Blade',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 159,
    attackBonus: 92,
    shadowBonus: 90,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 26,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_26.png',
    sprite32Url: '/assets/weapons/items/sword_26_32.png',
    priceGold: 2100,
    priceGems: 15,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_27',
    name: 'Golden Guard Rapier',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 135,
    attackBonus: 72,
    shadowBonus: 66,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 27,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_27.png',
    sprite32Url: '/assets/weapons/items/sword_27_32.png',
    priceGold: 1370,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_28',
    name: 'Heavy Marauder Machete',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 82,
    attackBonus: 34,
    shadowBonus: 24,
    critChance: 0.16,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 28,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_28.png',
    sprite32Url: '/assets/weapons/items/sword_28_32.png',
    priceGold: 400,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_29',
    name: 'Dual Serpent Hookblade',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 180,
    attackBonus: 110,
    shadowBonus: 108,
    critChance: 0.4,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 29,
    hiltOffset: [6.0, 84.8],
    tipOffset: [90.7, 7.3],
    spriteUrl: '/assets/weapons/items/sword_29.png',
    sprite32Url: '/assets/weapons/items/sword_29_32.png',
    priceGold: 2850,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_30',
    name: 'Legion Iron Gladius',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 70,
    attackBonus: 25,
    shadowBonus: 18,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 30,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_30.png',
    sprite32Url: '/assets/weapons/items/sword_30_32.png',
    priceGold: 250,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_31',
    name: 'Silver Crest Bastard Sword',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 120,
    attackBonus: 60,
    shadowBonus: 54,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 31,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_31.png',
    sprite32Url: '/assets/weapons/items/sword_31_32.png',
    priceGold: 1010,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_32',
    name: 'Gilded Court Rapier',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 32,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_32.png',
    sprite32Url: '/assets/weapons/items/sword_32_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_33',
    name: 'Crimson Vanguard Sword',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 130,
    attackBonus: 68,
    shadowBonus: 62,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 33,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_33.png',
    sprite32Url: '/assets/weapons/items/sword_33_32.png',
    priceGold: 1250,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_34',
    name: 'Thief Stiletto',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 1,
    basePower: 86,
    attackBonus: 37,
    shadowBonus: 26,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 34,
    hiltOffset: [7.3, 87.7],
    tipOffset: [87.7, 7.3],
    spriteUrl: '/assets/weapons/items/sword_34.png',
    sprite32Url: '/assets/weapons/items/sword_34_32.png',
    priceGold: 450,
    priceGems: 0,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_35',
    name: 'Bronze Infantry Broadsword',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 70,
    attackBonus: 25,
    shadowBonus: 18,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efb775',
      glow: '#efb775',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 35,
    hiltOffset: [4.9, 89.3],
    tipOffset: [89.3, 4.9],
    spriteUrl: '/assets/weapons/items/sword_35.png',
    sprite32Url: '/assets/weapons/items/sword_35_32.png',
    priceGold: 250,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_36',
    name: 'Twilight Void Katana',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 195,
    attackBonus: 125,
    shadowBonus: 125,
    critChance: 0.35,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 36,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_36.png',
    sprite32Url: '/assets/weapons/items/sword_36_32.png',
    priceGold: 3800,
    priceGems: 45,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_37',
    name: 'Sunburst Star Maceblade',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 5,
    basePower: 180,
    attackBonus: 110,
    shadowBonus: 108,
    critChance: 0.34,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ab5c1c',
      glow: '#ab5c1c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 37,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_37.png',
    sprite32Url: '/assets/weapons/items/sword_37_32.png',
    priceGold: 2850,
    priceGems: 15,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_38',
    name: 'Highland Bronze Shortsword',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 82,
    attackBonus: 34,
    shadowBonus: 24,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efb775',
      glow: '#efb775',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 38,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_38.png',
    sprite32Url: '/assets/weapons/items/sword_38_32.png',
    priceGold: 400,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_39',
    name: 'Royal Crest Rapier',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 39,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_39.png',
    sprite32Url: '/assets/weapons/items/sword_39_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_40',
    name: 'Blazing Ember Sickle',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 145,
    attackBonus: 80,
    shadowBonus: 78,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ef3a0c',
      glow: '#ef3a0c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 40,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_40.png',
    sprite32Url: '/assets/weapons/items/sword_40_32.png',
    priceGold: 1600,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_41',
    name: 'Golden Sun Katana',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 135,
    attackBonus: 72,
    shadowBonus: 66,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 41,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_41.png',
    sprite32Url: '/assets/weapons/items/sword_41_32.png',
    priceGold: 1370,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_42',
    name: 'Spiked Fortress Crossguard',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 105,
    attackBonus: 48,
    shadowBonus: 42,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 42,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_42.png',
    sprite32Url: '/assets/weapons/items/sword_42_32.png',
    priceGold: 650,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_43',
    name: 'Gilded Royal Foil',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 1,
    basePower: 82,
    attackBonus: 34,
    shadowBonus: 24,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 43,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_43.png',
    sprite32Url: '/assets/weapons/items/sword_43_32.png',
    priceGold: 400,
    priceGems: 0,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_44',
    name: 'Magma Forged Broadsword',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 5,
    basePower: 173,
    attackBonus: 104,
    shadowBonus: 102,
    critChance: 0.4,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 44,
    hiltOffset: [4.9, 89.3],
    tipOffset: [82.9, 9.5],
    spriteUrl: '/assets/weapons/items/sword_44.png',
    sprite32Url: '/assets/weapons/items/sword_44_32.png',
    priceGold: 2600,
    priceGems: 15,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_45',
    name: 'Emerald Dragon Fang',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 180,
    attackBonus: 110,
    shadowBonus: 108,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#3c9f9c',
      glow: '#3c9f9c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 45,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_45.png',
    sprite32Url: '/assets/weapons/items/sword_45_32.png',
    priceGold: 2850,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_46',
    name: 'Iron Guillotine Cleaver',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efb775',
      glow: '#efb775',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 46,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_46.png',
    sprite32Url: '/assets/weapons/items/sword_46_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_47',
    name: 'Monastery Training Shinai',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 1,
    basePower: 78,
    attackBonus: 31,
    shadowBonus: 22,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 47,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_47.png',
    sprite32Url: '/assets/weapons/items/sword_47_32.png',
    priceGold: 350,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_48',
    name: 'Ancient Ironwood Greatsword',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 5,
    basePower: 145,
    attackBonus: 80,
    shadowBonus: 78,
    critChance: 0.37,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#a56243',
      secondary: '#2a1d0d',
      glow: '#a56243',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 48,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_48.png',
    sprite32Url: '/assets/weapons/items/sword_48_32.png',
    priceGold: 1600,
    priceGems: 15,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_49',
    name: 'Void Singularity Edge',
    slot: 'weapon',
    rarity: 'mythic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 10,
    basePower: 275,
    attackBonus: 190,
    shadowBonus: 197,
    critChance: 0.45,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#6b3ab3',
      glow: '#6b3ab3',
    },
    perks: ['Primordial Cataclysm'],
    iconName: 'Swords',
    swordIndex: 49,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_49.png',
    sprite32Url: '/assets/weapons/items/sword_49_32.png',
    priceGold: 6800,
    priceGems: 90,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_50',
    name: 'Golden Willow Dao',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 110,
    attackBonus: 52,
    shadowBonus: 46,
    critChance: 0.28,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 50,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_50.png',
    sprite32Url: '/assets/weapons/items/sword_50_32.png',
    priceGold: 770,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_51',
    name: 'Curved Tiger Talon',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 115,
    attackBonus: 56,
    shadowBonus: 50,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 51,
    hiltOffset: [4.3, 90.7],
    tipOffset: [84.8, 6.0],
    spriteUrl: '/assets/weapons/items/sword_51.png',
    sprite32Url: '/assets/weapons/items/sword_51_32.png',
    priceGold: 890,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_52',
    name: 'Jade Lotus Ring-Blade',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 173,
    attackBonus: 104,
    shadowBonus: 102,
    critChance: 0.34,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#3c9f9c',
      glow: '#3c9f9c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 52,
    hiltOffset: [4.3, 90.7],
    tipOffset: [86.1, 7.1],
    spriteUrl: '/assets/weapons/items/sword_52.png',
    sprite32Url: '/assets/weapons/items/sword_52_32.png',
    priceGold: 2600,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_53',
    name: 'Molten Flare Sabre',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 180,
    attackBonus: 110,
    shadowBonus: 108,
    critChance: 0.37,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efac28',
      glow: '#efac28',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 53,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_53.png',
    sprite32Url: '/assets/weapons/items/sword_53_32.png',
    priceGold: 2850,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_54',
    name: 'High Sovereign Claymore',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 8,
    basePower: 195,
    attackBonus: 125,
    shadowBonus: 125,
    critChance: 0.41,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 54,
    hiltOffset: [7.3, 87.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_54.png',
    sprite32Url: '/assets/weapons/items/sword_54_32.png',
    priceGold: 3800,
    priceGems: 45,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_55',
    name: 'Heavy Stonecutter Blade',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 135,
    attackBonus: 72,
    shadowBonus: 66,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 55,
    hiltOffset: [4.9, 89.3],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_55.png',
    sprite32Url: '/assets/weapons/items/sword_55_32.png',
    priceGold: 1370,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_56',
    name: 'Shadow Forged Bastard',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 145,
    attackBonus: 80,
    shadowBonus: 78,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#684c3c',
      glow: '#684c3c',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 56,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_56.png',
    sprite32Url: '/assets/weapons/items/sword_56_32.png',
    priceGold: 1600,
    priceGems: 15,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_57',
    name: 'Celestial Comet Blade',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 225,
    attackBonus: 149,
    shadowBonus: 152,
    critChance: 0.38,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#3c9f9c',
      glow: '#3c9f9c',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 57,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_57.png',
    sprite32Url: '/assets/weapons/items/sword_57_32.png',
    priceGold: 5150,
    priceGems: 45,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_58',
    name: 'Ossuary Bone Stiletto',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 82,
    attackBonus: 34,
    shadowBonus: 24,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 58,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_58.png',
    sprite32Url: '/assets/weapons/items/sword_58_32.png',
    priceGold: 400,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_59',
    name: 'Sacred Phoenix Edge',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 245,
    attackBonus: 165,
    shadowBonus: 170,
    critChance: 0.44,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 59,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_59.png',
    sprite32Url: '/assets/weapons/items/sword_59_32.png',
    priceGold: 6050,
    priceGems: 45,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_60',
    name: 'Runic Iron Broadsword',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.22,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 60,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_60.png',
    sprite32Url: '/assets/weapons/items/sword_60_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_61',
    name: 'Shattered Astral Shard',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 205,
    attackBonus: 133,
    shadowBonus: 134,
    critChance: 0.38,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#c084e2',
      glow: '#c084e2',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 61,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_61.png',
    sprite32Url: '/assets/weapons/items/sword_61_32.png',
    priceGold: 4250,
    priceGems: 45,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_62',
    name: 'Ivory Archon Claymore',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 8,
    basePower: 215,
    attackBonus: 141,
    shadowBonus: 143,
    critChance: 0.41,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efb775',
      glow: '#efb775',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 62,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_62.png',
    sprite32Url: '/assets/weapons/items/sword_62_32.png',
    priceGold: 4700,
    priceGems: 45,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_63',
    name: 'Dragon Emperor Dao',
    slot: 'weapon',
    rarity: 'legendary' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 8,
    basePower: 225,
    attackBonus: 149,
    shadowBonus: 152,
    critChance: 0.44,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efac28',
      glow: '#efac28',
    },
    perks: ['Lifesteal Siphon'],
    iconName: 'Swords',
    swordIndex: 63,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_63.png',
    sprite32Url: '/assets/weapons/items/sword_63_32.png',
    priceGold: 5150,
    priceGems: 45,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_64',
    name: 'Solar Flare Falchion',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 145,
    attackBonus: 80,
    shadowBonus: 78,
    critChance: 0.4,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efac28',
      glow: '#efac28',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 64,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_64.png',
    sprite32Url: '/assets/weapons/items/sword_64_32.png',
    priceGold: 1600,
    priceGems: 15,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_65',
    name: 'Emerald Viper Edge',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 115,
    attackBonus: 56,
    shadowBonus: 50,
    critChance: 0.25,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ab5c1c',
      glow: '#ab5c1c',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 65,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_65.png',
    sprite32Url: '/assets/weapons/items/sword_65_32.png',
    priceGold: 890,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_66',
    name: 'Bronze Practice Foil',
    slot: 'weapon',
    rarity: 'common' as GearRarity,
    faction: 'legion' as Faction,
    weaponType: 'greatsword' as WeaponType,
    level: 1,
    basePower: 74,
    attackBonus: 28,
    shadowBonus: 20,
    critChance: 0.2,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#ef3a0c',
      glow: '#ef3a0c',
    },
    perks: ['Iron Edge'],
    iconName: 'Swords',
    swordIndex: 66,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_66.png',
    sprite32Url: '/assets/weapons/items/sword_66_32.png',
    priceGold: 300,
    priceGems: 0,
    shadowAffinityName: 'Legion Mastery',
  },
  {
    id: 'sword_market_67',
    name: 'Royal Gilded Cutlass',
    slot: 'weapon',
    rarity: 'rare' as GearRarity,
    faction: 'dynasty' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 3,
    basePower: 125,
    attackBonus: 64,
    shadowBonus: 58,
    critChance: 0.31,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efac28',
      glow: '#efac28',
    },
    perks: ['Shadow Bleed'],
    iconName: 'Swords',
    swordIndex: 67,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_67.png',
    sprite32Url: '/assets/weapons/items/sword_67_32.png',
    priceGold: 1130,
    priceGems: 0,
    shadowAffinityName: 'Dynasty Mastery',
  },
  {
    id: 'sword_market_68',
    name: 'Crimson Duelist Rapier',
    slot: 'weapon',
    rarity: 'epic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 5,
    basePower: 173,
    attackBonus: 104,
    shadowBonus: 102,
    critChance: 0.37,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#efd8a1',
      glow: '#efd8a1',
    },
    perks: ['Critical Surge'],
    iconName: 'Swords',
    swordIndex: 68,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_68.png',
    sprite32Url: '/assets/weapons/items/sword_68_32.png',
    priceGold: 2600,
    priceGems: 15,
    shadowAffinityName: 'Heralds Mastery',
  },
  {
    id: 'sword_market_69',
    name: 'Primordial Void Scimitar',
    slot: 'weapon',
    rarity: 'mythic' as GearRarity,
    faction: 'heralds' as Faction,
    weaponType: 'katana' as WeaponType,
    level: 10,
    basePower: 275,
    attackBonus: 190,
    shadowBonus: 197,
    critChance: 0.42,
    description: 'A finely tempered 32x32 pixel art blade forged in the fires of the shadow rift.',
    lore: 'Cut out from the master artisan armory collection. Its edge carries the unbroken spirit of mortal and void masters alike.',
    colorScheme: {
      primary: '#2a1d0d',
      secondary: '#a58c27',
      glow: '#a58c27',
    },
    perks: ['Primordial Cataclysm'],
    iconName: 'Swords',
    swordIndex: 69,
    hiltOffset: [4.3, 90.7],
    tipOffset: [90.7, 4.3],
    spriteUrl: '/assets/weapons/items/sword_69.png',
    sprite32Url: '/assets/weapons/items/sword_69_32.png',
    priceGold: 6800,
    priceGems: 90,
    shadowAffinityName: 'Heralds Mastery',
  },
];
